import { defineMap, docLink } from 'onboarding-map';

/*
 * A map of onboarding-map itself: how someone goes from "I have a subject to
 * onboard people into" to "a map I can send". It is the example the docs show,
 * and it is written by hand in one file, like any other map.
 */

const docs = docLink('docs', 'https://chidirnweke.github.io/onboarding-map/');
const github = docLink('github', 'https://github.com/ChidiRnweke/onboarding-map');

export default defineMap({
  id: 'onboarding-map',
  version: '0.1.0',
  title: 'Make your own onboarding map',
  motto: 'Bring your subject. Get a map.',
  labels: {
    intro: 'One file describes your subject. The package draws it as a map you can send.',
    period: 'Part',
  },

  kinds: [
    { id: 'concept', label: 'Idea', plural: 'Ideas', description: 'Something to understand.' },
    { id: 'tool', label: 'Step', plural: 'Steps', description: 'Something you do.' },
  ],
  periods: [
    {
      period: 1,
      title: 'See and describe',
      summary: 'Look at an example, then say what you are onboarding someone into.',
    },
    { period: 2, title: 'Shape and share', summary: 'Draw one path, check the map, and publish it.' },
  ],

  documents: [
    {
      id: 'docs',
      title: 'The documentation',
      date: '2026-09-27',
      url: 'https://chidirnweke.github.io/onboarding-map/',
    },
    {
      id: 'github',
      title: 'The repository',
      date: '2026-09-27',
      url: 'https://github.com/ChidiRnweke/onboarding-map',
    },
  ],

  goal: {
    title: 'A map you can send',
    statement: 'Your subject written as one file, drawn as a map a newcomer can follow.',
    doneWhen: 'Someone follows your map from the first stage to the last and ends up with something real.',
    story:
      'A map is two things at once. It is everything a newcomer will run into, so nothing feels hidden. And it is one path through that, so they are never deciding what to learn next.',
    modules: [
      {
        id: 'example',
        title: 'A walked example',
        purpose: 'You cannot judge a map until you have followed one.',
        dependsOn: [],
        builtFrom: ['starter-example', 'physics-example', 'example-data'],
        produces: ['An example you have read and clicked through'],
      },
      {
        id: 'brief',
        title: 'A brief',
        purpose: 'The map is only as good as what you decide it is about.',
        dependsOn: ['example'],
        relations: [{ to: 'example', verb: 'is clearer after' }],
        builtFrom: ['audience', 'outcome', 'sources'],
        produces: ['Who is onboarding, what they should be able to do, and where the material is'],
      },
      {
        id: 'mapfile',
        title: 'A first draft',
        purpose: 'The subject becomes a file, by hand or with an agent.',
        dependsOn: ['brief'],
        relations: [{ to: 'brief', verb: 'is written from' }],
        builtFrom: ['map-file', 'agent-skills', 'draft-prompt'],
        produces: ['A map.ts with regions and items'],
      },
      {
        id: 'route',
        title: 'One path',
        purpose: 'Choosing a single route is what keeps the map from overwhelming the reader.',
        dependsOn: ['mapfile'],
        relations: [{ to: 'mapfile', verb: 'is drawn on' }],
        builtFrom: ['route', 'stages', 'checkpoint', 'goal'],
        produces: ['A journey with a beginning, stages, and a way to know it is done'],
      },
      {
        id: 'checked',
        title: 'A checked map',
        purpose: 'Links break and content ages; the tool finds both.',
        dependsOn: ['route'],
        relations: [{ to: 'route', verb: 'checks' }],
        builtFrom: ['validate', 'audit', 'changelog'],
        produces: ['A map whose references resolve and whose content is current'],
      },
      {
        id: 'published',
        title: 'A published map',
        purpose: 'A map nobody can open is not a map.',
        dependsOn: ['checked'],
        relations: [{ to: 'checked', verb: 'is built from' }],
        builtFrom: ['build', 'host'],
        produces: ['A static site you can send to the newcomer'],
      },
    ],
  },

  domains: [
    { id: 'start', label: 'Start', tagline: 'See one first', order: 0, color: '#22c55e' },
    { id: 'subject', label: 'Your subject', tagline: 'What you bring', order: 1, color: '#14b8a6' },
    { id: 'agent', label: 'Your agent', tagline: 'The heavy lifting', order: 2, color: '#a855f7' },
    { id: 'map', label: 'The map', tagline: 'The file and its path', order: 3, color: '#3b82f6' },
    { id: 'tool', label: 'Checking and sharing', tagline: 'The tool', order: 4, color: '#f59e0b' },
    { id: 'project', label: 'This project', tagline: 'Where it comes from', order: 5, color: '#64748b' },
  ],

  nodes: [
    {
      id: 'the-idea',
      label: 'Why a map',
      domain: 'start',
      kind: 'category',
      status: 'path',
      summary: 'The problem the map solves.',
    },
    {
      id: 'newcomer-problem',
      label: 'The reading pile',
      domain: 'start',
      kind: 'concept',
      status: 'context',
      parent: 'the-idea',
      summary:
        'Everything a newcomer needs is written down somewhere, but as separate documents for people who already know the system.',
      refs: [{ doc: 'docs' }],
    },
    {
      id: 'one-route',
      label: 'One path',
      domain: 'start',
      kind: 'concept',
      status: 'context',
      parent: 'the-idea',
      summary:
        'The map shows everything, but asks the newcomer to follow only one route. The rest is there to recognise, not to learn first.',
    },

    {
      id: 'examples',
      label: 'Examples',
      domain: 'start',
      kind: 'category',
      status: 'path',
      summary: 'Two maps to look at before you make your own.',
    },
    {
      id: 'starter-example',
      refs: [{ doc: 'docs' }],
      label: 'Starter example',
      domain: 'start',
      kind: 'concept',
      status: 'path',
      parent: 'examples',
      stage: 'see',
      summary: 'The smallest useful map: two regions, a handful of items, two stages.',
      docs: [docs('The starter template', 'user-guide/examples/')],
    },
    {
      id: 'physics-example',
      refs: [{ doc: 'docs' }],
      label: 'Physics example',
      domain: 'start',
      kind: 'concept',
      status: 'path',
      parent: 'examples',
      stage: 'see',
      summary: 'A complete map outside software: motion, forces and energy, with a full route.',
      docs: [docs('The physics template', 'user-guide/examples/')],
    },
    {
      id: 'example-data',
      refs: [{ doc: 'docs' }],
      label: 'The data behind it',
      domain: 'start',
      kind: 'concept',
      status: 'path',
      parent: 'examples',
      stage: 'see',
      summary: 'Every map is one file. The examples page shows the map and the file next to each other.',
      docs: [docs('Examples, map and data', 'user-guide/examples/')],
    },

    {
      id: 'your-subject',
      label: 'Your subject',
      domain: 'subject',
      kind: 'category',
      status: 'path',
      summary: 'What you decide the map is about.',
    },
    {
      id: 'audience',
      refs: [{ doc: 'docs' }],
      docs: [docs('How it works', 'user-guide/how-it-works/')],
      label: 'Who is arriving',
      domain: 'subject',
      kind: 'concept',
      status: 'path',
      parent: 'your-subject',
      stage: 'brief',
      summary: 'Who is being onboarded, and what they already know. It sets the level of every summary.',
    },
    {
      id: 'outcome',
      refs: [{ doc: 'docs' }],
      docs: [docs('How it works', 'user-guide/how-it-works/')],
      label: 'What they can do',
      domain: 'subject',
      kind: 'concept',
      status: 'path',
      parent: 'your-subject',
      stage: 'brief',
      summary: 'The thing that exists when the onboarding is done. The stages exist to build it.',
    },
    {
      id: 'sources',
      label: 'Your material',
      docs: [docs('Working with your agent', 'user-guide/working-with-your-agent/')],
      domain: 'subject',
      kind: 'concept',
      status: 'path',
      parent: 'your-subject',
      stage: 'brief',
      summary:
        'Notes, slides, a syllabus, a codebase. The map is based on these, and cites them, so it can be refreshed later.',
      refs: [{ doc: 'docs' }],
    },
    {
      id: 'existing-docs',
      label: 'Docs you already have',
      domain: 'subject',
      kind: 'concept',
      status: 'context',
      parent: 'your-subject',
      summary:
        'Existing documentation stays where it is. The map links to it at the right moment instead of copying it.',
    },

    {
      id: 'the-file',
      label: 'The file',
      domain: 'map',
      kind: 'category',
      status: 'path',
      summary: 'One file holds the whole map.',
    },
    {
      id: 'map-file',
      refs: [{ doc: 'docs' }],
      label: 'map.ts',
      domain: 'map',
      kind: 'tool',
      status: 'path',
      parent: 'the-file',
      stage: 'draft',
      summary:
        'Your subject as one TypeScript file. Types come from the package, so mistakes show up in your editor.',
      docs: [github('The templates', '/tree/main/templates')],
    },
    {
      id: 'hand-write',
      docs: [docs('Writing a map', 'user-guide/writing-a-map/')],
      label: 'Write it yourself',
      domain: 'map',
      kind: 'tool',
      status: 'alternative',
      alternativeTo: 'map-file',
      parent: 'the-file',
      summary:
        'You can write the file by hand. Nothing here needs an agent; the format is the whole interface.',
    },
    {
      id: 'json-map',
      docs: [docs('Writing a map', 'user-guide/writing-a-map/')],
      label: 'map.json',
      domain: 'map',
      kind: 'tool',
      status: 'alternative',
      alternativeTo: 'map-file',
      parent: 'the-file',
      summary: 'Use JSON instead of TypeScript when another tool needs to write the map.',
    },

    {
      id: 'the-journey',
      label: 'The journey',
      domain: 'map',
      kind: 'category',
      status: 'path',
      summary: 'The one path through everything.',
    },
    {
      id: 'route',
      label: 'The route',
      refs: [{ doc: 'docs' }],
      docs: [docs('How it works', 'user-guide/how-it-works/')],
      domain: 'map',
      kind: 'concept',
      status: 'path',
      parent: 'the-journey',
      stage: 'route',
      summary:
        'The items the newcomer actually uses, in order. Everything else is context or a choice you did not take.',
    },
    {
      id: 'stages',
      refs: [{ doc: 'docs' }],
      docs: [docs('How it works', 'user-guide/how-it-works/')],
      label: 'Stages',
      domain: 'map',
      kind: 'concept',
      status: 'path',
      parent: 'the-journey',
      stage: 'route',
      summary:
        'The route cut into stages. Each one is small, and follows the same shape: do something, watch what happens, then read about it.',
    },
    {
      id: 'checkpoint',
      refs: [{ doc: 'docs' }],
      docs: [docs('How it works', 'user-guide/how-it-works/')],
      label: 'Checkpoint',
      domain: 'map',
      kind: 'concept',
      status: 'path',
      parent: 'the-journey',
      stage: 'route',
      summary: 'How the newcomer knows a stage is finished: something they can see, not a feeling.',
    },
    {
      id: 'goal',
      refs: [{ doc: 'docs' }],
      docs: [docs('How it works', 'user-guide/how-it-works/')],
      label: 'The goal',
      domain: 'map',
      kind: 'concept',
      status: 'path',
      parent: 'the-journey',
      stage: 'route',
      summary: 'What the whole journey builds, shown as parts that fill in as the stages go.',
    },
    {
      id: 'context-items',
      label: 'Good to know it exists',
      domain: 'map',
      kind: 'concept',
      status: 'context',
      parent: 'the-journey',
      summary: 'Items off the route. Cheap to add, and they make the map honest about what is out there.',
    },

    {
      id: 'with-an-agent',
      label: 'With an agent',
      domain: 'agent',
      kind: 'category',
      status: 'path',
      summary: 'Let a coding agent do the first draft.',
    },
    {
      id: 'agent-skills',
      refs: [{ doc: 'docs' }],
      label: 'The skills',
      domain: 'agent',
      kind: 'concept',
      status: 'path',
      parent: 'with-an-agent',
      stage: 'draft',
      summary:
        'The package installs instructions for Claude Code, Codex and other tools: how to write, edit and refresh a map.',
      docs: [github('The skills', '/tree/main/skills')],
    },
    {
      id: 'draft-prompt',
      refs: [{ doc: 'docs' }],
      docs: [docs('Working with your agent', 'user-guide/working-with-your-agent/')],
      label: 'Ask for a draft',
      domain: 'agent',
      kind: 'tool',
      status: 'path',
      parent: 'with-an-agent',
      stage: 'draft',
      summary:
        'Point the agent at your material and ask it to turn it into a map. Read the result; you decide the route.',
    },

    {
      id: 'the-checks',
      label: 'The checks',
      domain: 'tool',
      kind: 'category',
      status: 'path',
      summary: 'The command line keeps the map true.',
    },
    {
      id: 'validate',
      refs: [{ doc: 'docs' }],
      label: 'validate',
      domain: 'tool',
      kind: 'tool',
      status: 'path',
      parent: 'the-checks',
      stage: 'check',
      summary: 'Checks that every reference in the file resolves, and names the ones that do not.',
      docs: [docs('Command line', 'reference/cli/')],
    },
    {
      id: 'audit',
      refs: [{ doc: 'docs' }],
      docs: [docs('Command line', 'reference/cli/')],
      label: 'audit',
      domain: 'tool',
      kind: 'tool',
      status: 'path',
      parent: 'the-checks',
      stage: 'check',
      summary:
        'Finds the content that has gone stale: dead links, missing sources, route items nobody is sent to.',
    },
    {
      id: 'changelog',
      refs: [{ doc: 'docs' }],
      docs: [docs('Command line', 'reference/cli/')],
      label: 'changelog',
      domain: 'tool',
      kind: 'tool',
      status: 'path',
      parent: 'the-checks',
      stage: 'check',
      summary: 'Shows what changed since the last commit, as a short summary for review.',
    },
    {
      id: 'dev-server',
      label: 'See it as you write',
      domain: 'tool',
      kind: 'tool',
      status: 'context',
      parent: 'the-checks',
      summary: 'The dev command serves the map and reloads it on every save.',
    },

    {
      id: 'publish',
      label: 'Publish',
      domain: 'tool',
      kind: 'category',
      status: 'path',
      summary: 'Turn the file into a site.',
    },
    {
      id: 'build',
      refs: [{ doc: 'docs' }],
      docs: [docs('Command line', 'reference/cli/')],
      label: 'build',
      domain: 'tool',
      kind: 'tool',
      status: 'path',
      parent: 'publish',
      stage: 'share',
      summary: 'Writes a static site: your map plus the app that draws it.',
    },
    {
      id: 'host',
      refs: [{ doc: 'docs' }],
      docs: [docs('Command line', 'reference/cli/')],
      label: 'Any static host',
      domain: 'tool',
      kind: 'concept',
      status: 'path',
      parent: 'publish',
      stage: 'share',
      summary:
        'The output is plain files. There is no server and no account; progress is kept in the reader’s browser.',
    },
    {
      id: 'static-shell',
      label: 'The app shell',
      domain: 'tool',
      kind: 'concept',
      status: 'context',
      parent: 'publish',
      summary: 'One prebuilt app renders any map. Your map file is all that changes.',
    },

    {
      id: 'codebase',
      label: 'The codebase',
      domain: 'project',
      kind: 'category',
      status: 'context',
      summary: 'What the package is made of.',
    },
    {
      id: 'core',
      label: 'The model',
      domain: 'project',
      kind: 'concept',
      status: 'context',
      parent: 'codebase',
      summary: 'Types, validation and derivation. It runs in Node and the browser, and has no UI.',
      docs: [github('src/core', '/tree/main/src/core')],
    },
    {
      id: 'cli',
      label: 'The command line',
      domain: 'project',
      kind: 'concept',
      status: 'context',
      parent: 'codebase',
      summary: 'init, dev, build, validate, changelog, audit, schema and skills install.',
    },
    {
      id: 'app-shell-code',
      label: 'The app',
      domain: 'project',
      kind: 'concept',
      status: 'context',
      parent: 'codebase',
      summary: 'The SvelteKit shell that draws the map and walks the stages.',
    },
    {
      id: 'templates-code',
      label: 'The templates',
      domain: 'project',
      kind: 'concept',
      status: 'context',
      parent: 'codebase',
      summary: 'starter and physics; the two examples this map points at.',
    },
    {
      id: 'docs-site',
      label: 'This documentation',
      domain: 'project',
      kind: 'concept',
      status: 'context',
      parent: 'codebase',
      summary:
        'Astro and Starlight, wearing the map’s own palette. The page you are reading is part of the repository.',
      docs: [github('docs', '/tree/main/docs')],
    },
  ],

  edges: [
    { from: 'agent-skills', to: 'sources', kind: 'drafts-from' },
    { from: 'validate', to: 'map-file', kind: 'checks' },
    { from: 'audit', to: 'map-file', kind: 'checks' },
    { from: 'build', to: 'map-file', kind: 'renders' },
    { from: 'route', to: 'outcome', kind: 'builds-toward' },
  ],

  stages: [
    {
      id: 'see',
      period: 1,
      order: 1,
      title: 'See one',
      feeling: 'I know what a finished map looks like.',
      task: 'Open the two examples and follow a stage or two.',
      delivers: ['example'],
      waypoints: ['starter-example', 'physics-example', 'example-data'],
      do: [
        'Open the examples page and click around the physics map.',
        {
          text: 'Switch to the data view and find one item in the file.',
          tip: 'The map and the file are shown side by side.',
          tipKind: 'reveal',
        },
      ],
      observe: [{ text: 'Which items are on the route, and which are just context?', note: true }],
      read: ['starter-example', 'example-data', 'one-route'],
      checkpoint: 'You can point at one item and say why it is on the route.',
      refs: [{ doc: 'docs' }],
    },
    {
      id: 'brief',
      period: 1,
      refs: [{ doc: 'docs' }],
      order: 2,
      title: 'Say what it is about',
      feeling: 'I can describe who this is for and what they should be able to do.',
      task: 'Write down who is arriving, what they can do at the end, and where the material lives.',
      delivers: ['brief'],
      waypoints: ['audience', 'outcome', 'sources'],
      do: [
        'Write one sentence for each: who, and what they can do at the end.',
        { text: 'List the documents, slides or repositories the map is based on.', note: true },
      ],
      observe: [{ text: 'Does the outcome describe something you could check, not a feeling?', note: true }],
      read: ['outcome', 'sources', 'existing-docs'],
      checkpoint: 'You have a short brief you could hand to another person.',
    },
    {
      id: 'draft',
      period: 2,
      refs: [{ doc: 'docs' }],
      order: 3,
      title: 'Draft the map',
      feeling: 'The subject exists as a file I can run.',
      task: 'Start a project and get a first version of the file, by hand or with an agent.',
      delivers: ['mapfile'],
      waypoints: ['agent-skills', 'draft-prompt', 'map-file'],
      do: [
        { text: 'Start a project from a template.', tip: 'npx onboarding-map init my-map' },
        {
          text: 'Ask your coding agent to turn your brief and sources into a map.',
          tip: 'Turn these notes into an onboarding map.',
          tipKind: 'copy',
        },
      ],
      observe: [{ text: 'What did the agent put on the route that you would not?', note: true }],
      read: ['map-file', 'agent-skills', 'hand-write'],
      checkpoint: 'The map opens in the dev server without errors.',
    },
    {
      id: 'route',
      period: 2,
      order: 4,
      title: 'Choose one path',
      feeling: 'I know exactly what the newcomer does, in order.',
      task: 'Mark the items the newcomer will use, and cut them into stages.',
      delivers: ['route'],
      waypoints: ['route', 'stages', 'checkpoint', 'goal'],
      do: [
        'Move anything the newcomer will not touch off the route.',
        'Cut the route into stages, each with one idea.',
      ],
      observe: [{ text: 'Does every stage end with something you can see?', note: true }],
      read: ['stages', 'checkpoint', 'goal', 'context-items'],
      checkpoint: 'Every stage has a checkpoint a newcomer could demonstrate.',
      refs: [{ doc: 'docs' }],
    },
    {
      id: 'check',
      period: 2,
      refs: [{ doc: 'docs' }],
      order: 5,
      title: 'Check it',
      feeling: 'I trust the map: it resolves, and I know what is unfinished.',
      task: 'Run the checks and fix what they report.',
      delivers: ['checked'],
      waypoints: ['validate', 'audit', 'changelog'],
      do: [
        { text: 'Validate and fix every error.', tip: 'npx onboarding-map validate --json' },
        { text: 'Audit for stale or unfinished content.', tip: 'npx onboarding-map audit' },
      ],
      observe: [{ text: 'What did the audit find that you had forgotten?', note: true }],
      read: ['validate', 'audit', 'changelog', 'dev-server'],
      checkpoint: 'validate reports no errors and you have read the audit findings.',
    },
    {
      id: 'share',
      period: 2,
      refs: [{ doc: 'docs' }],
      order: 6,
      title: 'Share it',
      feeling: 'I can send this to the next person who joins.',
      task: 'Build the static site and put it somewhere people can open it.',
      delivers: ['published'],
      waypoints: ['build', 'host'],
      do: [
        { text: 'Build the site.', tip: 'npx onboarding-map build' },
        'Upload the output folder to any static host.',
      ],
      observe: [{ text: 'Open the map on a phone. Is the route still easy to follow?', note: true }],
      read: ['build', 'host', 'static-shell'],
      checkpoint: 'Someone else opens your map and starts the first stage.',
    },
  ],
});
